pipeline {
    agent { label 'master' }

    stages {
        stage('Prepare ENV') {
            steps {
                script {
                    if ("${tagToCreate}".isEmpty()) {
                        throw new Exception("tagToCreate field is missing, please check")
                    }

                    env.JGIT_TAG = "${tagToCreate}.${BUILD_NUMBER}.fun-wp-${APP_ENV}"

                    if ("${APP_ENV}" == "development") {
                        env.JGIT_TAG = "${tagToCreate}.${BUILD_NUMBER}.fun-wp-dev"
                    }
                }
            }
        }

        stage('Set Tags') {
            steps {
                dir('wordpress') {
                    git branch: '${WORK_BRANCH}',
                    credentialsId: "${GIT_CREDS}",
                    url: 'git@github.com:funi-main/funimation-wordpress.git'
                    sh 'git tag -a -f ${JGIT_TAG} -m "Creating version from ${BUILD_URL}"'
                    //sshagent(["${GIT_CREDS}"]) {
                    //    sh "git push git@github.com:funi-main/funimation-wordpress.git ${JGIT_TAG}"
                    //}
                }

                git branch: 'venue',
                credentialsId: "${GIT_CREDS}",
                url: 'git@github.com:funi-main/source2-main.git'
            }
        }

        stage('Build') {
            steps {
                sh ''' #!/bin/bash
                $(aws ecr get-login --region=us-west-2 --no-include-email)
                rm -rf ./blog/blog
                mv wordpress ./blog/blog
                cp /var/lib/jenkins/GeoLite2-City.mmdb blog/
                '''

                /*sh '''#!/bin/bash
                docker build \
                -t ${ECR_URL}/venue-blog-${APP_ENV}:latest \
                -t ${ECR_URL}/venue-blog-${APP_ENV}:${JGIT_TAG} \
                -f blog/Dockerfile ./blog
                #docker push ${ECR_URL}/source2base-${APP_ENV_NAME}:latest
                #docker push ${ECR_URL}/source2base-${APP_ENV_NAME}:${JGIT_TAG}
                '''*/
            }
        }

        stage('Deploy') {
            steps {
                sh ''' #!/bin/bash
                if [ $APP_ENV = "development" ]; then
                echo $APP_ENV
                #ecs deploy VENUE-DEV blog -t ${JGIT_TAG} --region us-west-2 || true
                fi

                if [ $APP_ENV = "qa" ]; then
                echo $APP_ENV
                #ecs deploy VENUE-QA blog -t ${JGIT_TAG} --region us-west-2 || true
                fi

                if [ $APP_ENV = "uat" ]; then
                echo $APP_ENV
                #ecs deploy VENUE-UAT blog -t ${JGIT_TAG} --region us-west-2 || true
                fi

                if [ $APP_ENV = "pre-prod" ]; then
                echo $APP_ENV
                #ecs deploy VENUE-PRE-PROD blog -t ${JGIT_TAG} --region us-west-2 || true
                fi
                '''
            }
        }
    }
}
