pipeline {
    agent any

    stages {
        stage('Prepare ENV') {
            steps {
                script {
                    if ("${tagToCreate}".isEmpty()) {
                        throw new Exception("tagToCreate field is missing, please check")
                    }

                    env.JGIT_TAG = "${tagToCreate}.${BUILD_NUMBER}.fun-wp-${APP_ENV}"

                    if ("${APP_ENV}" == "development") {
                        env.JGIT_TAG = "${tagToCreate}.${BUILD_NUMBER}.fun-wp-dev"
                    }
                }

                dir ('test') {
                    git branch: '${WORK_BRANCH}',
                    credentialsId: "${GIT_CREDS}",
                    url: 'git@github.com:funi-main/funimation-wordpress.git'
                    sh 'git tag -a -f ${JGIT_TAG} -m "Creating version from ${BUILD_URL}"'
                    //sshagent(["${GIT_CREDS}"]) {
                    //    sh "git push git@github.com:funi-main/funimation-wordpress.git ${JGIT_TAG}"
                    //}
                }

            }
        }
    }
}
